//! http://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-scroll.html

//Autogenerated

use hyper::client::Client;
use hyper::client::response::Response;
use hyper::error::Result;

use RequestParams;

pub fn delete_scroll_id<'a>(client: &'a mut Client, req: RequestParams,
                        scroll_id: &'a str) -> Result<Response>{
    let url_qry = &req.get_url_qry();
    let base = &req.base_url;
    let mut url_fmtd =
        String::with_capacity(base.len() + 16 + scroll_id.len() +
                                  url_qry.len());
    url_fmtd.push_str(base);
    url_fmtd.push_str("/_search/scroll/");
    url_fmtd.push_str(scroll_id);
    url_fmtd.push_str(url_qry);
    let res = client.delete(&url_fmtd).headers(req.headers);
    res.send()
}
pub fn delete<'a>(client: &'a mut Client, req: RequestParams) -> Result<Response>{
    let url_qry = &req.get_url_qry();
    let base = &req.base_url;
    let mut url_fmtd = String::with_capacity(base.len() + 15 + url_qry.len());
    url_fmtd.push_str(base);
    url_fmtd.push_str("/_search/scroll");
    url_fmtd.push_str(url_qry);
    let res = client.delete(&url_fmtd).headers(req.headers);
    res.send()
}
