//Autogenerated
use hyper::Client;
pub fn get(base: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 15);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_search/scroll");
    url_fmtd
}
pub fn post(base: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 15);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_search/scroll");
    url_fmtd
}
pub fn get_scroll_id(base: String, scroll_id: String) -> String{
    let mut url_fmtd =
        String::with_capacity(base.len() + 16 + scroll_id.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_search/scroll/");
    url_fmtd.push_str(&scroll_id);
    url_fmtd
}
pub fn post_scroll_id(base: String, scroll_id: String) -> String{
    let mut url_fmtd =
        String::with_capacity(base.len() + 16 + scroll_id.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_search/scroll/");
    url_fmtd.push_str(&scroll_id);
    url_fmtd
}
