//Autogenerated
pub fn get(base: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 23);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/pending_tasks");
    url_fmtd
}
