//Autogenerated
pub fn post(base: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 17);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/reroute");
    url_fmtd
}
