//Autogenerated

use hyper::header::{Headers, ContentType};
use hyper::client::response::Response;
use hyper::error::Result;

pub fn get(client: &'a mut hyper::Client, base: String) -> Result<Response>{
    let mut url_fmtd = String::with_capacity(base.len() + 15);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/state");
    let mut headers = Headers::new();
    headers.set(ContentType::json());
    let res = client.get(&url_fmtd).headers(headers);
    res.send()
}
pub fn get_metric(client: &'a mut hyper::Client, base: String, metric: String)
 -> Result<Response>{
    let mut url_fmtd = String::with_capacity(base.len() + 16 + metric.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/state/");
    url_fmtd.push_str(&metric);
    let mut headers = Headers::new();
    headers.set(ContentType::json());
    let res = client.get(&url_fmtd).headers(headers);
    res.send()
}
pub fn get_metric_index(client: &'a mut hyper::Client, base: String,
                    metric: String, index: String) -> Result<Response>{
    let mut url_fmtd =
        String::with_capacity(base.len() + 16 + 1 + metric.len() +
                                  index.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/state/");
    url_fmtd.push_str(&metric);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&index);
    let mut headers = Headers::new();
    headers.set(ContentType::json());
    let res = client.get(&url_fmtd).headers(headers);
    res.send()
}
