//Autogenerated
use hyper::Client;
pub fn get(base: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 15);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/stats");
    url_fmtd
}
pub fn get_node_id(base: String, node_id: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 22 + node_id.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/stats/nodes/");
    url_fmtd.push_str(&node_id);
    url_fmtd
}
