//Autogenerated
pub fn get(base: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 15);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/state");
    url_fmtd
}
pub fn get_metric(base: String, metric: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 16 + metric.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/state/");
    url_fmtd.push_str(&metric);
    url_fmtd
}
pub fn get_metric_index(base: String, metric: String, index: String) -> String{
    let mut url_fmtd =
        String::with_capacity(base.len() + 16 + 1 + metric.len() +
                                  index.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/state/");
    url_fmtd.push_str(&metric);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&index);
    url_fmtd
}
