//Autogenerated

use hyper::header::{Headers, ContentType};
use hyper::client::response::Response;
use hyper::error::Result;

pub fn head(client: &'a mut hyper::Client, base: String) -> Result<Response>{
    let mut url_fmtd = String::with_capacity(base.len() + 1);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/");
    let mut headers = Headers::new();
    headers.set(ContentType::json());
    let res = client.head(&url_fmtd).headers(headers);
    res.send()
}
