//Autogenerated

use hyper::header::{Headers, ContentType};
use hyper::client::response::Response;
use hyper::error::Result;

pub fn head_index_type(client: &'a mut hyper::Client, base: String, index: String,
                   type: String) -> Result<Response>{
    let mut url_fmtd =
        String::with_capacity(base.len() + 1 + 1 + index.len() + type.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&index);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&type);
    let mut headers = Headers::new();
    headers.set(ContentType::json());
    let res = client.head(&url_fmtd).headers(headers);
    res.send()
}
