//Autogenerated
pub fn get_index(base: String, index: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 1 + index.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&index);
    url_fmtd
}
pub fn get_index_feature(base: String, index: String, feature: String) -> String{
    let mut url_fmtd =
        String::with_capacity(base.len() + 1 + 1 + index.len() +
                                  feature.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&index);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&feature);
    url_fmtd
}
