//Autogenerated
use hyper::Client;
pub fn post(base: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 9);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_aliases");
    url_fmtd
}
