//Autogenerated
use hyper::Client;
pub fn post(base: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 6);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_bulk");
    url_fmtd
}
pub fn put(base: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 6);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_bulk");
    url_fmtd
}
pub fn post_index(base: String, index: String) -> String{
    let mut url_fmtd =
        String::with_capacity(base.len() + 1 + 6 + index.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&index);
    url_fmtd.push_str("/_bulk");
    url_fmtd
}
pub fn put_index(base: String, index: String) -> String{
    let mut url_fmtd =
        String::with_capacity(base.len() + 1 + 6 + index.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&index);
    url_fmtd.push_str("/_bulk");
    url_fmtd
}
pub fn post_index_type(base: String, index: String, type: String) -> String{
    let mut url_fmtd =
        String::with_capacity(base.len() + 1 + 1 + 6 + index.len() +
                                  type.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&index);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&type);
    url_fmtd.push_str("/_bulk");
    url_fmtd
}
pub fn put_index_type(base: String, index: String, type: String) -> String{
    let mut url_fmtd =
        String::with_capacity(base.len() + 1 + 1 + 6 + index.len() +
                                  type.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&index);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&type);
    url_fmtd.push_str("/_bulk");
    url_fmtd
}
