[package]
name = "search"
version = "0.0.0"
authors = ["Stephan Buys <stephan.buys@panoptix.co.za>"]

[dependencies]
elastic_queries = { path = "../../" }
env_logger = "0.6"
futures = "0.1.15"
futures-cpupool = "0.1.5"
serde = "~1"
serde_derive = "~1"
serde_json = "~1"
tokio = "~0.1"

[dependencies.timestrings]
git = "https://github.com/stephanbuys/timestrings.git"
version = "*"

[dependencies.elastic]
path = "../../../../src/elastic/"
version = "*"

[dependencies.elastic_derive]
path = "../../../../src/elastic_derive/"
version = "*"

