[package]
name = "search"
version = "0.0.0"
authors = ["Stephan Buys <stephan.buys@panoptix.co.za>"]

[dependencies]
elastic-queries = { version = "*", path = "../../" }
env_logger = "0.4.3"
futures = "0.1.15"
futures-cpupool = "0.1.5"
serde = "~1"
serde_derive = "~1"
serde_json = "~1"
tokio-core = "0.1.9"

[dependencies.timestrings]
git = "https://github.com/stephanbuys/timestrings.git"
version = "*"

[dependencies.elastic]
git = "https://github.com/elastic-rs/elastic.git"
version = "*"

[dependencies.elastic_derive]
git = "https://github.com/elastic-rs/elastic.git"
version = "*"

