[package]
name = "prepare"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
publish = false

[dependencies]
elastic = { version = "*", path = "../../src/elastic" }
elastic_derive = { version = "*", path = "../../src/elastic_derive" }
serde = "*"
serde_derive = "*"
