//! http://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-reroute.html

//Autogenerated

use hyper::client::Client;
use hyper::header::{Headers, ContentType};
use hyper::client::response::Response;
use hyper::error::Result;

pub fn post<'a>(client: &'a mut Client, base: &'a str, body: &'a str)
 -> Result<Response>{
    let mut url_fmtd = String::with_capacity(base.len() + 17);
    url_fmtd.push_str(base);
    url_fmtd.push_str("/_cluster/reroute");
    let mut headers = Headers::new();
    headers.set(ContentType::json());
    let res = client.post(&url_fmtd).headers(headers).body(body);
    res.send()
}
