//! http://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-stats.html

//Autogenerated

use hyper::client::Client;
use hyper::header::{Headers, ContentType};
use hyper::client::response::Response;
use hyper::error::Result;

pub fn get_node_id<'a>(client: &'a mut Client, base: String, node_id: String)
 -> Result<Response>{
    let mut url_fmtd = String::with_capacity(base.len() + 22 + node_id.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/stats/nodes/");
    url_fmtd.push_str(&node_id);
    let mut headers = Headers::new();
    headers.set(ContentType::json());
    let res = client.get(&url_fmtd).headers(headers);
    res.send()
}
pub fn get<'a>(client: &'a mut Client, base: String) -> Result<Response>{
    let mut url_fmtd = String::with_capacity(base.len() + 15);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/stats");
    let mut headers = Headers::new();
    headers.set(ContentType::json());
    let res = client.get(&url_fmtd).headers(headers);
    res.send()
}
