//Autogenerated
pub fn get(base: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 26);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/nodes/hotthreads");
    url_fmtd
}
pub fn get(base: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 27);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/nodes/hot_threads");
    url_fmtd
}
pub fn get_node_id(base: String, node_id: String) -> String{
    let mut url_fmtd =
        String::with_capacity(base.len() + 16 + 11 + node_id.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/nodes/");
    url_fmtd.push_str(&node_id);
    url_fmtd.push_str("/hotthreads");
    url_fmtd
}
pub fn get_node_id(base: String, node_id: String) -> String{
    let mut url_fmtd =
        String::with_capacity(base.len() + 16 + 12 + node_id.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cluster/nodes/");
    url_fmtd.push_str(&node_id);
    url_fmtd.push_str("/hot_threads");
    url_fmtd
}
pub fn get(base: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 18);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_nodes/hotthreads");
    url_fmtd
}
pub fn get(base: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 19);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_nodes/hot_threads");
    url_fmtd
}
pub fn get_node_id(base: String, node_id: String) -> String{
    let mut url_fmtd =
        String::with_capacity(base.len() + 8 + 11 + node_id.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_nodes/");
    url_fmtd.push_str(&node_id);
    url_fmtd.push_str("/hotthreads");
    url_fmtd
}
pub fn get_node_id(base: String, node_id: String) -> String{
    let mut url_fmtd =
        String::with_capacity(base.len() + 8 + 12 + node_id.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_nodes/");
    url_fmtd.push_str(&node_id);
    url_fmtd.push_str("/hot_threads");
    url_fmtd
}
