//Autogenerated
pub fn get(base: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 7);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_nodes");
    url_fmtd
}
pub fn get_node_id(base: String, node_id: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 8 + node_id.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_nodes/");
    url_fmtd.push_str(&node_id);
    url_fmtd
}
pub fn get_metric(base: String, metric: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 8 + metric.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_nodes/");
    url_fmtd.push_str(&metric);
    url_fmtd
}
pub fn get_node_id_metric(base: String, node_id: String, metric: String) -> String{
    let mut url_fmtd =
        String::with_capacity(base.len() + 8 + 1 + node_id.len() +
                                  metric.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_nodes/");
    url_fmtd.push_str(&node_id);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&metric);
    url_fmtd
}
