//! http://www.elastic.co/guide/en/elasticsearch/reference/master/indices-templates.html

//Autogenerated

use hyper::client::Client;
use hyper::client::response::Response;
use hyper::error::Result;

use RequestParams;

pub fn delete_name<'a>(client: &'a mut Client, req: RequestParams, name: &'a str)
 -> Result<Response>{
    let url_qry = &req.get_url_qry();
    let base = &req.base_url;
    let mut url_fmtd =
        String::with_capacity(base.len() + 11 + name.len() + url_qry.len());
    url_fmtd.push_str(base);
    url_fmtd.push_str("/_template/");
    url_fmtd.push_str(name);
    url_fmtd.push_str(url_qry);
    let res = client.delete(&url_fmtd).headers(req.headers);
    res.send()
}
