//! http://www.elastic.co/guide/en/elasticsearch/reference/master/indices-delete-index.html

//Autogenerated

use hyper::client::Client;
#[allow(unused_imports)]
use hyper::client::Body;
use hyper::client::response::Response;
use hyper::error::Result;

use ::RequestParams;

pub fn delete_index<'a>(client: &'a mut Client, req: RequestParams,
                    index: &'a str) -> Result<Response>{
    let url_qry = &req.get_url_qry();
    let base = &req.base_url;
    let mut url_fmtd =
        String::with_capacity(base.len() + 1 + index.len() + url_qry.len());
    url_fmtd.push_str(base);
    url_fmtd.push_str("/");
    url_fmtd.push_str(index);
    url_fmtd.push_str(url_qry);
    let res = client.delete(&url_fmtd).headers(req.headers);
    res.send()
}
