//! http://www.elastic.co/guide/en/elasticsearch/reference/master/indices-update-settings.html

//Autogenerated

use hyper::client::Client;
use hyper::client::response::Response;
use hyper::error::Result;

use RequestParams;

pub fn put<'a>(client: &'a mut Client, req: RequestParams, body: &'a str)
 -> Result<Response>{
    let url_qry = &req.get_url_qry();
    let base = &req.base_url;
    let mut url_fmtd = String::with_capacity(base.len() + 10 + url_qry.len());
    url_fmtd.push_str(base);
    url_fmtd.push_str("/_settings");
    url_fmtd.push_str(url_qry);
    let res = client.put(&url_fmtd).headers(req.headers).body(body);
    res.send()
}
pub fn put_index<'a>(client: &'a mut Client, req: RequestParams, index: &'a str,
                 body: &'a str) -> Result<Response>{
    let url_qry = &req.get_url_qry();
    let base = &req.base_url;
    let mut url_fmtd =
        String::with_capacity(base.len() + 1 + 10 + index.len() +
                                  url_qry.len());
    url_fmtd.push_str(base);
    url_fmtd.push_str("/");
    url_fmtd.push_str(index);
    url_fmtd.push_str("/_settings");
    url_fmtd.push_str(url_qry);
    let res = client.put(&url_fmtd).headers(req.headers).body(body);
    res.send()
}
