//Autogenerated
use hyper::Client;
pub fn delete_lang_id(base: String, lang: String, id: String) -> String{
    let mut url_fmtd =
        String::with_capacity(base.len() + 10 + 1 + lang.len() + id.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_scripts/");
    url_fmtd.push_str(&lang);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&id);
    url_fmtd
}
