//Autogenerated
pub fn get(base: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 15);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cat/fielddata");
    url_fmtd
}
pub fn get_fields(base: String, fields: String) -> String{
    let mut url_fmtd = String::with_capacity(base.len() + 16 + fields.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cat/fielddata/");
    url_fmtd.push_str(&fields);
    url_fmtd
}
