//Autogenerated

use hyper::header::{Headers, ContentType};
use hyper::client::response::Response;
use hyper::error::Result;

pub fn get_repository(client: &'a mut hyper::Client, base: String,
                  repository: String) -> Result<Response>{
    let mut url_fmtd =
        String::with_capacity(base.len() + 16 + repository.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_cat/snapshots/");
    url_fmtd.push_str(&repository);
    let mut headers = Headers::new();
    headers.set(ContentType::json());
    let res = client.get(&url_fmtd).headers(headers);
    res.send()
}
