//Autogenerated
use hyper::Client;
pub fn post_index_type_id(base: String, index: String, type: String, id: String)
 -> String{
    let mut url_fmtd =
        String::with_capacity(base.len() + 1 + 1 + 1 + 8 + index.len() +
                                  type.len() + id.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&index);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&type);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&id);
    url_fmtd.push_str("/_update");
    url_fmtd
}
