[package]
name = "elastic_codegen"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
publish = false

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
syn = { version = "*", features = ["full"] }
quote = "*"
Inflector = "*"

[dev-dependencies]
json_str = "*"
