//Autogenerated

use hyper::header::{Headers, ContentType};
use hyper::client::response::Response;
use hyper::error::Result;

pub fn get(client: &'a mut hyper::Client, base: String) -> Result<Response>{
    let mut url_fmtd = String::with_capacity(base.len() + 18);
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_snapshot/_status");
    let mut headers = Headers::new();
    headers.set(ContentType::json());
    let res = client.get(&url_fmtd).headers(headers);
    res.send()
}
pub fn get_repository(client: &'a mut hyper::Client, base: String,
                  repository: String) -> Result<Response>{
    let mut url_fmtd =
        String::with_capacity(base.len() + 11 + 8 + repository.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_snapshot/");
    url_fmtd.push_str(&repository);
    url_fmtd.push_str("/_status");
    let mut headers = Headers::new();
    headers.set(ContentType::json());
    let res = client.get(&url_fmtd).headers(headers);
    res.send()
}
pub fn get_repository_snapshot(client: &'a mut hyper::Client, base: String,
                           repository: String, snapshot: String)
 -> Result<Response>{
    let mut url_fmtd =
        String::with_capacity(base.len() + 11 + 1 + 8 + repository.len() +
                                  snapshot.len());
    url_fmtd.push_str(&base);
    url_fmtd.push_str("/_snapshot/");
    url_fmtd.push_str(&repository);
    url_fmtd.push_str("/");
    url_fmtd.push_str(&snapshot);
    url_fmtd.push_str("/_status");
    let mut headers = Headers::new();
    headers.set(ContentType::json());
    let res = client.get(&url_fmtd).headers(headers);
    res.send()
}
